"""add_constraints_and_max_lengths

Revision ID: 4ee15708ac01
Revises: e685f0027c5b
Create Date: 2026-06-04 22:09:37.478883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee15708ac01'
down_revision: Union[str, Sequence[str], None] = 'e685f0027c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_recipe_cook_date', 'meal_logs', ['recipe_id', 'cooked_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_recipe_cook_date', 'meal_logs', type_='unique')
    # ### end Alembic commands ###
